name: Deploy Backend to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/CULTURA_MAIN/server
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            rm -rf node_modules package-lock.json
            npm install
            pm2 restart server --update-env
            pm2 save
